package com.teach.teachingsys.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.ResultSetExtractor;
import org.springframework.stereotype.Service;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class DatabaseBackupService {

    private final JdbcTemplate jdbcTemplate;

    public String exportDatabase() {
        StringBuilder sql = new StringBuilder();
        
        // 1. Disable Foreign Key Checks
        sql.append("/*\n");
        sql.append(" * Database Backup\n");
        sql.append(" * Generated by TeachingSys\n");
        sql.append(" */\n\n");
        sql.append("SET NAMES utf8mb4;\n");
        sql.append("SET FOREIGN_KEY_CHECKS = 0;\n\n");

        try {
            // 2. Get all table names
            List<String> tables = jdbcTemplate.queryForList("SHOW TABLES", String.class);

            for (String tableName : tables) {
                // 3. Export Structure (DDL)
                exportTableStructure(tableName, sql);
                
                // 4. Export Data (DML)
                exportTableData(tableName, sql);
            }

        } catch (Exception e) {
            log.error("Error exporting database", e);
            throw new RuntimeException("Database export failed: " + e.getMessage());
        }

        // 5. Re-enable Foreign Key Checks
        sql.append("\nSET FOREIGN_KEY_CHECKS = 1;\n");
        
        return sql.toString();
    }

    private void exportTableStructure(String tableName, StringBuilder sql) {
        sql.append("-- ----------------------------\n");
        sql.append("-- Table structure for ").append(tableName).append("\n");
        sql.append("-- ----------------------------\n");
        
        sql.append("DROP TABLE IF EXISTS `").append(tableName).append("`;\n");
        
        jdbcTemplate.query("SHOW CREATE TABLE `" + tableName + "`", (ResultSetExtractor<Void>) rs -> {
            if (rs.next()) {
                String createTableSql = rs.getString(2);
                sql.append(createTableSql).append(";\n\n");
            }
            return null;
        });
    }

    private void exportTableData(String tableName, StringBuilder sql) {
        sql.append("-- ----------------------------\n");
        sql.append("-- Records of ").append(tableName).append("\n");
        sql.append("-- ----------------------------\n");

        jdbcTemplate.query("SELECT * FROM `" + tableName + "`", (ResultSetExtractor<Void>) rs -> {
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            while (rs.next()) {
                sql.append("INSERT INTO `").append(tableName).append("` VALUES (");
                
                for (int i = 1; i <= columnCount; i++) {
                    Object value = rs.getObject(i);
                    if (value == null) {
                        sql.append("NULL");
                    } else {
                        String strValue = value.toString();
                        // Handle escaping
                        strValue = strValue.replace("\\", "\\\\"); // Backslash
                        strValue = strValue.replace("'", "\\'");   // Single quote
                        strValue = strValue.replace("\r", "\\r");
                        strValue = strValue.replace("\n", "\\n");
                        
                        sql.append("'").append(strValue).append("'");
                    }
                    
                    if (i < columnCount) {
                        sql.append(", ");
                    }
                }
                sql.append(");\n");
            }
            return null;
        });
        sql.append("\n");
    }
}
